ID_COLS = ["CONTRAGENTID", "IDENTIFYCODE"]

LEAKAGE_KEYWORDS = [
    "REVENUE",
    "GROSS_PROFIT",
    "OPER_PROFIT",
    "NET_PROFIT",
    "INCOME"
]

SUFFIX_PRIORITY = ["_NORM", "_CUR", "_DIF", "_PREV"]
